### YamlMime:ManagedReference
items:
- uid: Yort.LatitudePay.InStore.LatitudePayEnvironment
  commentId: T:Yort.LatitudePay.InStore.LatitudePayEnvironment
  id: LatitudePayEnvironment
  parent: Yort.LatitudePay.InStore
  children:
  - Yort.LatitudePay.InStore.LatitudePayEnvironment.Production
  - Yort.LatitudePay.InStore.LatitudePayEnvironment.Uat
  langs:
  - csharp
  - vb
  name: LatitudePayEnvironment
  nameWithType: LatitudePayEnvironment
  fullName: Yort.LatitudePay.InStore.LatitudePayEnvironment
  type: Enum
  source:
    remote:
      path: src/LatitudePayEnvironment.cs
      branch: master
      repo: https://github.com/Yortw/Yort.LatitudePay.InStore
    id: LatitudePayEnvironment
    path: LatitudePayEnvironment.cs
    startLine: 5
  assemblies:
  - Yort.LatitudePay.InStore
  namespace: Yort.LatitudePay.InStore
  summary: "\nA enum providing a list of environments for the LatitudePay API.\n"
  example: []
  syntax:
    content: public enum LatitudePayEnvironment
    content.vb: Public Enum LatitudePayEnvironment
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Yort.LatitudePay.InStore.LatitudePayEnvironment.Uat
  commentId: F:Yort.LatitudePay.InStore.LatitudePayEnvironment.Uat
  id: Uat
  parent: Yort.LatitudePay.InStore.LatitudePayEnvironment
  langs:
  - csharp
  - vb
  name: Uat
  nameWithType: LatitudePayEnvironment.Uat
  fullName: Yort.LatitudePay.InStore.LatitudePayEnvironment.Uat
  type: Field
  source:
    remote:
      path: src/LatitudePayEnvironment.cs
      branch: master
      repo: https://github.com/Yortw/Yort.LatitudePay.InStore
    id: Uat
    path: LatitudePayEnvironment.cs
    startLine: 10
  assemblies:
  - Yort.LatitudePay.InStore
  namespace: Yort.LatitudePay.InStore
  summary: "\nThe test/sandbox API.\n"
  example: []
  syntax:
    content: Uat = 0
    return:
      type: Yort.LatitudePay.InStore.LatitudePayEnvironment
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Yort.LatitudePay.InStore.LatitudePayEnvironment.Production
  commentId: F:Yort.LatitudePay.InStore.LatitudePayEnvironment.Production
  id: Production
  parent: Yort.LatitudePay.InStore.LatitudePayEnvironment
  langs:
  - csharp
  - vb
  name: Production
  nameWithType: LatitudePayEnvironment.Production
  fullName: Yort.LatitudePay.InStore.LatitudePayEnvironment.Production
  type: Field
  source:
    remote:
      path: src/LatitudePayEnvironment.cs
      branch: master
      repo: https://github.com/Yortw/Yort.LatitudePay.InStore
    id: Production
    path: LatitudePayEnvironment.cs
    startLine: 14
  assemblies:
  - Yort.LatitudePay.InStore
  namespace: Yort.LatitudePay.InStore
  summary: "\nThe live/production API.\n"
  example: []
  syntax:
    content: Production = 1
    return:
      type: Yort.LatitudePay.InStore.LatitudePayEnvironment
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Yort.LatitudePay.InStore
  commentId: N:Yort.LatitudePay.InStore
  name: Yort.LatitudePay.InStore
  nameWithType: Yort.LatitudePay.InStore
  fullName: Yort.LatitudePay.InStore
- uid: Yort.LatitudePay.InStore.LatitudePayEnvironment
  commentId: T:Yort.LatitudePay.InStore.LatitudePayEnvironment
  parent: Yort.LatitudePay.InStore
  name: LatitudePayEnvironment
  nameWithType: LatitudePayEnvironment
  fullName: Yort.LatitudePay.InStore.LatitudePayEnvironment
