using System;
using Newtonsoft.Json;

namespace Yort.LatitudePay.InStore
{
	/// <summary>
	/// Represents a response to a request to refund some or all of an accepted payment plan (via <see cref="LatitudePayClient.CreateRefundAsync(LatitudePayCreateRefundRequest)"/>).
	/// </summary>
	/// <seealso cref="LatitudePayCreateRefundRequest"/>
	/// <seealso cref="LatitudePayClient.CreateRefundAsync(LatitudePayCreateRefundRequest)"/>
	public class LatitudePayCreateRefundResponse
	{
		/// <summary>
		/// Gets or sets the refund identifier generated by LatitudePay.
		/// </summary>
		/// <value>
		/// The refund identifier.
		/// </value>
		[JsonProperty("refundId")]
		public string? RefundId { get; set; }

		/// <summary>
		/// Gets or sets the date and time the refund was created.
		/// </summary>
		/// <value>
		/// The refund date.
		/// </value>
		[JsonProperty("refundDate")]
		public DateTime RefundDate { get; set; }

		/// <summary>
		/// Gets or sets the merchant reference for the refund as provided in the request.
		/// </summary>
		/// <value>
		/// The reference.
		/// </value>		[JsonProperty("reference")]
		public string? Reference { get; set; }

		/// <summary>
		/// Gets or sets the fees charged to the retailer for this refund.
		/// </summary>
		/// <value>
		/// The commission amount.
		/// </value>
		[JsonProperty("commissionAmount")]
		public decimal CommissionAmount { get; set; }
	}
}
