name: Yort.LatitudePay.InStore.Build

on: 
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    env:
      LatitudePay_ApiKey: ${{ secrets.LatitudePay_ApiKey }}    
      LatitudePay_ApiSecret: ${{ secrets.LatitudePay_ApiSecret }}
      LatitudePay_TestMobileNumber: ${{ secrets.LatitudePay_TestMobileNumber }}
      Coveralls_Token: ${{ secrets.Coveralls_Token }}   

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Build with dotnet (src\Yort.LatitudePay.InStore.sln)
      run: dotnet build src\Yort.LatitudePay.InStore.sln --configuration Release --nologo
    - name: Run Tests
      run: dotnet test src\Yort.LatitudePay.InStore.sln --verbosity normal --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput="Tests/TestResults/"
    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.6.7
    - name: Generate Code Coverage Report
      run: reportgenerator "-reports:Tests\TestResults\**\coverage.cobertura.xml" "-targetdir:Tests\TestResults\Reports" --reporttypes:"Cobertura;Xml;Html" 
    - name: Install Coveralls Upload
      run: dotnet tool install -g coveralls.net --version 2.0.0
    - name: Upload coverage to Coveralls.IO
      run: csmacnz.Coveralls --reportgenerator -i "Tests\TestResults\Reports" --repoTokenVariable Coveralls_Token --commitId $Env:GITHUB_SHA --commitBranch $Env:GITHUB_REF --commitAuthor $Env:GITHUB_ACTOR --jobId $Env:GITHUB_RUN_ID
