on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-prerelease[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: windows-latest
    env:
      LatitudePay_ApiKey: ${{ secrets.LatitudePay_ApiKey }}    
      LatitudePay_ApiSecret: ${{ secrets.LatitudePay_ApiSecret }}
      LatitudePay_TestMobileNumber: ${{ secrets.LatitudePay_TestMobileNumber }}
      Coveralls_Token: ${{ secrets.Coveralls_Token }}   
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
    - name: Extract version from tag
      uses: Amadevus/pwsh-script@v1
      id: getVersion
      with:
        script: '("${{steps.tag.outputs.tag}}").Split("v")[1]'
    - name: Display Version
      run: echo "${{steps.getVersion.outputs.result}}"
    - name: Build
      run: dotnet build src/Yort.LatitudePay.InStore.sln --configuration Release --nologo /p:Version=${{steps.getVersion.outputs.result}} /p:NuGetVersion=${{steps.getVersion.outputs.result}}
    - name: Test
      run: dotnet test src/Yort.LatitudePay.InStore.sln --verbosity normal --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput="Tests/TestResults/"
    - name: Push
      run: dotnet nuget push src/bin/Release/Yort.LatitudePay.InStore.${{steps.getVersion.outputs.result}}.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
