on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LatitudePay_ApiKey: ${{ secrets.LatitudePay_ApiKey }}    
      LatitudePay_ApiSecret: ${{ secrets.LatitudePay_ApiSecret }}
      LatitudePay_TestMobileNumber: ${{ secrets.LatitudePay_TestMobileNumber }}
      Coveralls_Token: ${{ secrets.Coveralls_Token }}   
      NUGET_TOKEN: ${{ secrets.Nuget_Token }}
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Display Version
      run: echo "${VERSION}"
    - name: Build
      run: dotnet build src/Yort.LatitudePay.InStore.sln --configuration Release --nologo /p:Version=${VERSION} /p:NuGetVersion=${VERSION}
    - name: Test
      run: dotnet test src/Yort.LatitudePay.InStore.sln --verbosity normal --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput="Tests/TestResults/"
    - name: Push
      run: dotnet nuget push src/bin/Release/Yort.LatitudePay.InStore.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
